name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.26.0'
        cache: true
    
    - name: Test
      run: go test ./analyzer/...
    
    - name: Build
      run: go build -o linterlog ./cmd/